### ISSUE TITLE
Question: Why 100% height doesn't work for <table> in TkinterWeb?

### ISSUE THREAD

**Issue by XcantloadX** [Andereoo/TkinterWeb#106]
I'm trying to implement a typical header-main-footer layout for my app using table layout. However, I can't get the table expand vertically.

Here's a minimal code:
```html
<style>
html, body {
    margin: 0;
    padding: 0;
    height: 100%;
}
.full {
    height: 100%;
    width: 100%;
}
.test {
    background-color: #e81b23;
    text-align: center;
}
</style>

<table class="full">
    <tbody class="full">
        <tr class="full">
            <td class="full test">
                1234
            </td>
        </tr>
    </tbody>
</table>

<div class="full test">
    1234
</div>
```
Expected result is **two red rectangle with the same height as viewport**.

Test result on IE6 and Firefox 2:
![image](https://github.com/user-attachments/assets/0a89d4da-76c3-4c94-a060-a4f2638eeb86)

Test result on modern Firefox:
![image](https://github.com/user-attachments/assets/17d04c21-b064-4b2e-b60f-29b969b91b00)

Test result on Hv3:
![image](https://github.com/user-attachments/assets/bd0e95fd-41fd-4ed1-b841-2cbf1a8c6561)

Test result on TkinterWeb:
![image](https://github.com/user-attachments/assets/067c4651-ab50-4701-8803-54472e65ed6a)

Is this a bug or something's wrong with my code?

**Comment by dshaw0004** [comment]
Is this problem resolved ?

**Comment by dshaw0004** [comment]
Is this problem resolved ?

**Comment by dshaw0004** [comment]
Is this problem resolved ?

**Comment by XcantloadX** [comment]
> Is this problem resolved ?

No. I didn't find any useful information on Google.

**Comment by Andereoo** [comment]
Hi! This seems to be a bug with the underlying Tkhtml engine. It has not seen development in years and I've noticed some bugs with tables and percentages over the years. I'm afraid that fixing this is beyond the scope of this project for the time being. 

The best workaround would be to find the height of the frame every time the window is resized, divide that by two, and run set the height of the table to that value in pixels:
```
import tkinter as tk
from tkinterweb import HtmlFrame

root = tk.Tk()

frame = HtmlFrame(root)

frame.load_html("""
<style>
    html, body {
        margin: 0;
        padding: 0;
        height: 100%;
    }
    .full {
        height: 100%;
        width: 100%;
    }
    .test {
        background-color: #e81b23;
        text-align: center;
        width: 100%;
    }
</style>

<table class="test">
    <tbody class="full">
        <tr class="full">
            <td class="full test">
                1234
            </td>
        </tr>
    </tbody>
</table>

<div class="test">
    1234
</div>""")
frame.pack(expand=True, fill="both")

def on_resize(event):
    frame.add_css(".test {height: "+str(int(event.height/2))+".px}")

frame.bind("<Configure>", on_resize)
root.mainloop()

```

It's a little bit hacky but works like a charm. I hope this helps!

**Comment by XcantloadX** [comment]
> Hi! This seems to be a bug with the underlying Tkhtml engine. It has not seen development in years and I've noticed some bugs with tables and percentages over the years. I'm afraid that fixing this is beyond the scope of this project for the time being.
> 
> The best workaround would be to find the height of the frame every time the window is resized, divide that by two, and run set the height of the table to that value in pixels:
> 
> ```
> import tkinter as tk
> from tkinterweb import HtmlFrame
> 
> root = tk.Tk()
> 
> frame = HtmlFrame(root)
> 
> frame.load_html("""
> <style>
>     html, body {
>         margin: 0;
>         padding: 0;
>         height: 100%;
>     }
>     .full {
>         height: 100%;
>         width: 100%;
>     }
>     .test {
>         background-color: #e81b23;
>         text-align: center;
>         width: 100%;
>     }
> </style>
> 
> <table class="test">
>     <tbody class="full">
>         <tr class="full">
>             <td class="full test">
>                 1234
>             </td>
>         </tr>
>     </tbody>
> </table>
> 
> <div class="test">
>     1234
> </div>""")
> frame.pack(expand=True, fill="both")
> 
> def on_resize(event):
>     frame.add_css(".test {height: "+str(int(event.height/2))+".px}")
> 
> frame.bind("<Configure>", on_resize)
> root.mainloop()
> ```
> 
> It's a little bit hacky but works like a charm. I hope this helps!

Thanks! This works.
