### ISSUE TITLE
Is there any way to change the text in a node?

### ISSUE THREAD

**Issue by Zamy846692** [Andereoo/TkinterWeb#107]
Hello, I am trying to figure out if there is any way of changing the text contents of a node? 
like this: `<H1></H1>` to `<H1>Changed</H1>`. 
I am aware that there is a way to _get_ text `get_node_text`, but is there any way of changing it, even if you have to replace it with another node or something?

EDIT:
I have forked the library and have been able to add this (among other things). Will upload once I figure out how to get `git push` to work on [MSYS2](https://packages.msys2.org/package/git) .

**Comment by Andereoo** [comment]
Sorry for the delay. Do let me know or submit a pull request when you get the changes uploaded!

**Comment by Zamy846692** [comment]
Done it, check Pull requests now.
