### ISSUE TITLE
Js2py execute_script with tkinterweb 

### ISSUE THREAD

**Issue by Dawlat1** [Andereoo/TkinterWeb#108]
Hi 
Is it possible to combine Js2py with tkinterweb  to load html and CSS file with tkinterweb and then use something like execute_script() to render the JavaScript in the html and CSS file?

**Comment by Andereoo** [comment]
Hi! Yes, that likely would be possible but I don't have the time right now to make it happen. However, if you wanted to try yourself and were looking for some tips on how to bridge the gap between js2py and the webpage itself I'd be happy to offer some advice!
