### ISSUE TITLE
Tkinter/Tkhtml bug?

### ISSUE THREAD

**Issue by maxim3007** [Andereoo/TkinterWeb#11]
Hello!
When HtmlFrame loads a website that contains emojis HtmlFrame and Tkinter are becoming very blurry and laggy.
Please fix this issue ;)
![img](https://user-images.githubusercontent.com/76749786/120925801-f4637780-c6e2-11eb-95f9-1ea3b7a8f6d1.png)

**Comment by Andereoo** [comment]
Hi!

Thank you for letting me know about this. Can you please provide me with a link to that website so I can troubleshoot on my end?

**Comment by maxim3007** [comment]
I've used `https://emojipedia.org/locked/` but also you can find this issue on all websites that contain emojis

**Comment by maxim3007** [comment]
Also I have a stack trace:

2021-06-06 18:03:33.938 Python[46090:1912077] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Unlocking Focus on wrong view (<_NSThemeZoomWidget: 0x7fb8fc25ce70>), expected <TKContentView: 0x7fb8fc260030>'
*** First throw call stack:
(
        0   CoreFoundation                      0x00007fff36e20b57 __exceptionPreprocess + 250
        1   libobjc.A.dylib                     0x00007fff6fce35bf objc_exception_throw + 48
        2   CoreFoundation                      0x00007fff36e209b5 +[NSException raise:format:] + 189
        3   AppKit                              0x00007fff34303f76 -[NSView unlockFocus] + 129
        4   AppKit                              0x00007fff34252495 -[NSControl mouseDown:] + 1444
        5   AppKit                              0x00007fff343c584f -[_NSThemeWidget mouseDown:] + 86
        6   AppKit                              0x00007fff342505f0 -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 4914
        7   AppKit                              0x00007fff341bae21 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 2612
        8   AppKit                              0x00007fff341ba1c9 -[NSWindow(NSEventRouting) sendEvent:] + 349
        9   AppKit                              0x00007fff341b8554 -[NSApplication(NSEvent) sendEvent:] + 352
        10  libtk8.6.dylib                      0x0000000104f5b3ee -[TKApplication(TKNotify) sendEvent:] + 39
        11  libtk8.6.dylib                      0x0000000104f5b787 TkMacOSXEventsCheckProc + 434
        12  libtcl8.6.dylib                     0x0000000104de8d06 Tcl_DoOneEvent + 316
        13  _tkinter.cpython-39-darwin.so       0x0000000104d1440e _tkinter_tkapp_mainloop + 382
        14  Python                              0x00000001042ed77a cfunction_vectorcall_FASTCALL + 218
        15  Python                              0x0000000104385a2c call_function + 1020
        16  Python                              0x0000000104382e12 _PyEval_EvalFrameDefault + 25186
        17  Python                              0x0000000104386603 _PyEval_EvalCode + 2611
        18  Python                              0x00000001042af9c1 _PyFunction_Vectorcall + 289
        19  Python                              0x00000001042b1a7a method_vectorcall + 202
        20  Python                              0x000000010438590c call_function + 732
        21  Python                              0x0000000104382e33 _PyEval_EvalFrameDefault + 25219
        22  Python                              0x0000000104386603 _PyEval_EvalCode + 2611
        23  Python                              0x000000010437ca8b PyEval_EvalCode + 139
        24  Python                              0x0000000104379912 builtin_exec + 626
        25  Python                              0x00000001042ed77a cfunction_vectorcall_FASTCALL + 218
        26  Python                              0x000000010438590c call_function + 732
        27  Python                              0x0000000104382ecb _PyEval_EvalFrameDefault + 25371
        28  Python                              0x0000000104386603 _PyEval_EvalCode + 2611
        29  Python                              0x00000001042af9c1 _PyFunction_Vectorcall + 289
        30  Python                              0x000000010438590c call_function + 732
        31  Python                              0x0000000104382ecb _PyEval_EvalFrameDefault + 25371
        32  Python                              0x0000000104386603 _PyEval_EvalCode + 2611
        33  Python                              0x00000001042af9c1 _PyFunction_Vectorcall + 289
        34  Python                              0x000000010438590c call_function + 732
        35  Python                              0x0000000104382f61 _PyEval_EvalFrameDefault + 25521
        36  Python                              0x0000000104386603 _PyEval_EvalCode + 2611
        37  Python                              0x00000001042af9c1 _PyFunction_Vectorcall + 289
        38  Python                              0x000000010438590c call_function + 732
        39  Python                              0x0000000104382f61 _PyEval_EvalFrameDefault + 25521
        40  Python                              0x00000001042afa38 function_code_fastcall + 104
        41  Python                              0x000000010438590c call_function + 732
        42  Python                              0x0000000104382ecb _PyEval_EvalFrameDefault + 25371
        43  Python                              0x00000001042afa38 function_code_fastcall + 104
        44  Python                              0x000000010438590c call_function + 732
        45  Python                              0x0000000104382e33 _PyEval_EvalFrameDefault + 25219
        46  Python                              0x0000000104386603 _PyEval_EvalCode + 2611
        47  Python                              0x000000010437ca8b PyEval_EvalCode + 139
        48  Python                              0x0000000104379912 builtin_exec + 626
        49  Python                              0x00000001042ed77a cfunction_vectorcall_FASTCALL + 218
        50  Python                              0x000000010438590c call_function + 732
        51  Python                              0x0000000104382ecb _PyEval_EvalFrameDefault + 25371
        52  Python                              0x0000000104386603 _PyEval_EvalCode + 2611
        53  Python                              0x00000001042af9c1 _PyFunction_Vectorcall + 289
        54  Python                              0x000000010438590c call_function + 732
        55  Python                              0x0000000104382ecb _PyEval_EvalFrameDefault + 25371
        56  Python                              0x0000000104386603 _PyEval_EvalCode + 2611
        57  Python                              0x00000001042af9c1 _PyFunction_Vectorcall + 289
        58  Python                              0x00000001043ebfa0 pymain_run_module + 208
        59  Python                              0x00000001043eb6b7 Py_RunMain + 1431
        60  Python                              0x00000001043ebcbf pymain_main + 223
        61  Python                              0x00000001043ebebb Py_BytesMain + 43
        62  libdyld.dylib                       0x00007fff70e8bcc9 start + 1
        63  ???                                 0x0000000000000009 0x0 + 9
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by maxim3007** [comment]
Also I have an error when opening sites with emojis:

2021-06-06 18:03:33.938 Python[46090:1912077] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Unlocking Focus on wrong view (<_NSThemeZoomWidget: 0x7fb8fc25ce70>), expected <TKContentView: 0x7fb8fc260030>'
*** First throw call stack:
(
        0   CoreFoundation                      0x00007fff36e20b57 __exceptionPreprocess + 250
        1   libobjc.A.dylib                     0x00007fff6fce35bf objc_exception_throw + 48
        2   CoreFoundation                      0x00007fff36e209b5 +[NSException raise:format:] + 189
        3   AppKit                              0x00007fff34303f76 -[NSView unlockFocus] + 129
        4   AppKit                              0x00007fff34252495 -[NSControl mouseDown:] + 1444
        5   AppKit                              0x00007fff343c584f -[_NSThemeWidget mouseDown:] + 86
        6   AppKit                              0x00007fff342505f0 -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 4914
        7   AppKit                              0x00007fff341bae21 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 2612
        8   AppKit                              0x00007fff341ba1c9 -[NSWindow(NSEventRouting) sendEvent:] + 349
        9   AppKit                              0x00007fff341b8554 -[NSApplication(NSEvent) sendEvent:] + 352
        10  libtk8.6.dylib                      0x0000000104f5b3ee -[TKApplication(TKNotify) sendEvent:] + 39
        11  libtk8.6.dylib                      0x0000000104f5b787 TkMacOSXEventsCheckProc + 434
        12  libtcl8.6.dylib                     0x0000000104de8d06 Tcl_DoOneEvent + 316
        13  _tkinter.cpython-39-darwin.so       0x0000000104d1440e _tkinter_tkapp_mainloop + 382
        14  Python                              0x00000001042ed77a cfunction_vectorcall_FASTCALL + 218
        15  Python                              0x0000000104385a2c call_function + 1020
        16  Python                              0x0000000104382e12 _PyEval_EvalFrameDefault + 25186
        17  Python                              0x0000000104386603 _PyEval_EvalCode + 2611
        18  Python                              0x00000001042af9c1 _PyFunction_Vectorcall + 289
        19  Python                              0x00000001042b1a7a method_vectorcall + 202
        20  Python                              0x000000010438590c call_function + 732
        21  Python                              0x0000000104382e33 _PyEval_EvalFrameDefault + 25219
        22  Python                              0x0000000104386603 _PyEval_EvalCode + 2611
        23  Python                              0x000000010437ca8b PyEval_EvalCode + 139
        24  Python                              0x0000000104379912 builtin_exec + 626
        25  Python                              0x00000001042ed77a cfunction_vectorcall_FASTCALL + 218
        26  Python                              0x000000010438590c call_function + 732
        27  Python                              0x0000000104382ecb _PyEval_EvalFrameDefault + 25371
        28  Python                              0x0000000104386603 _PyEval_EvalCode + 2611
        29  Python                              0x00000001042af9c1 _PyFunction_Vectorcall + 289
        30  Python                              0x000000010438590c call_function + 732
        31  Python                              0x0000000104382ecb _PyEval_EvalFrameDefault + 25371
        32  Python                              0x0000000104386603 _PyEval_EvalCode + 2611
        33  Python                              0x00000001042af9c1 _PyFunction_Vectorcall + 289
        34  Python                              0x000000010438590c call_function + 732
        35  Python                              0x0000000104382f61 _PyEval_EvalFrameDefault + 25521
        36  Python                              0x0000000104386603 _PyEval_EvalCode + 2611
        37  Python                              0x00000001042af9c1 _PyFunction_Vectorcall + 289
        38  Python                              0x000000010438590c call_function + 732
        39  Python                              0x0000000104382f61 _PyEval_EvalFrameDefault + 25521
        40  Python                              0x00000001042afa38 function_code_fastcall + 104
        41  Python                              0x000000010438590c call_function + 732
        42  Python                              0x0000000104382ecb _PyEval_EvalFrameDefault + 25371
        43  Python                              0x00000001042afa38 function_code_fastcall + 104
        44  Python                              0x000000010438590c call_function + 732
        45  Python                              0x0000000104382e33 _PyEval_EvalFrameDefault + 25219
        46  Python                              0x0000000104386603 _PyEval_EvalCode + 2611
        47  Python                              0x000000010437ca8b PyEval_EvalCode + 139
        48  Python                              0x0000000104379912 builtin_exec + 626
        49  Python                              0x00000001042ed77a cfunction_vectorcall_FASTCALL + 218
        50  Python                              0x000000010438590c call_function + 732
        51  Python                              0x0000000104382ecb _PyEval_EvalFrameDefault + 25371
        52  Python                              0x0000000104386603 _PyEval_EvalCode + 2611
        53  Python                              0x00000001042af9c1 _PyFunction_Vectorcall + 289
        54  Python                              0x000000010438590c call_function + 732
        55  Python                              0x0000000104382ecb _PyEval_EvalFrameDefault + 25371
        56  Python                              0x0000000104386603 _PyEval_EvalCode + 2611
        57  Python                              0x00000001042af9c1 _PyFunction_Vectorcall + 289
        58  Python                              0x00000001043ebfa0 pymain_run_module + 208
        59  Python                              0x00000001043eb6b7 Py_RunMain + 1431
        60  Python                              0x00000001043ebcbf pymain_main + 223
        61  Python                              0x00000001043ebebb Py_BytesMain + 43
        62  libdyld.dylib                       0x00007fff70e8bcc9 start + 1
        63  ???                                 0x0000000000000009 0x0 + 9
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by Andereoo** [comment]
Hi!

This seems to be a bug with Tkhtml's emoji rendering. I've had trouble with that in the past with certain fonts, but I can't reproduce this issue on my system.

It looks like you are using MacOS. Is that right? 
If you are zooming the widget, try loading the website without zooming and let me know what happens.

Thanks.

**Comment by maxim3007** [comment]
Yep, I am using macOS Catalina.
I will try to reproduce this issue on my windows VM

**Comment by Andereoo** [comment]
I found this: https://bugs.python.org/issue35209.
Check it out and see if it fixes your problem.

On second thought, it seems that this is actually a Tk bug. It looks like you are encountering an old bug for Tk 8.5.x on macOS. It seems that Homebrew's Python ships with an outdated Tk version, while newer Tk versions have fixed this issue. If you can, try installing Python from python.org and see if you can reproduce this issue.

**Comment by maxim3007** [comment]
it seems this is not my problem because I downloaded python from python.org and tcl/tk version on my computer is 8.6.
Also I've found that stack trace appearing after frame resizing.

**Comment by maxim3007** [comment]
it seems this is not my problem because I downloaded python from python.org and tcl/tk version on my computer is 8.6.
Also I've found that stack trace is appearing after frame resizing.

**Comment by maxim3007** [comment]
I also have an error on win 7 32-bit python 3.7.4 from python.org
<img width="692" alt="issue" src="https://user-images.githubusercontent.com/76749786/120930797-7fe70380-c6f7-11eb-88c9-ef951c84b9e0.png">

**Comment by maxim3007** [comment]
And I've tested it on ubuntu 64-bit python 3.8 from apt:

![issue2](https://user-images.githubusercontent.com/76749786/120931116-e15ba200-c6f8-11eb-9688-5e53c6ed495d.png)

**Comment by Andereoo** [comment]
Hi,

Tkinter does have a number of issues with emojis. 

Thanks for the error messages in Linux and Windows. I see what is going wrong now.  
It is a known problem of Tkinter/Tcl that it only supports characters from the Basic Multilingual Plane (BMP). That includes unicode code points between U+0000 and U+FFFF. Emojis tend to be beyond U+FFFF, and therefore cause Tkinter to crash. Of course, TkinterWeb is not exempt from this limitation.

While many websites have started using characters beyond these limits, Tkinter hasn't adapted.  
To answer the question in the title of this issue, I'd say this is a Tkinter bug (or if not a bug, a limitation). 

I have had issues in the past with TkinterWeb crashing on Ubuntu when loading emojis above Tcl's range. I have worked around Tkinter's limitations by running `sudo apt-get install fonts-symbola` and then `sudo apt remove --purge fonts-noto-color-emoji`. For whatever reason that seems to have fixed these issues. See if that works for you on Ubuntu. There may be a similar workaround for Mac/Windows, but I'm not sure.

I'm going to look into a way to remove characters that are above Tkinter's range. This means that your emojis would not be displayed, but at least Tkinter won't crash. Past that I'm afraid there isn't much I can do about this. I'll let you know if I come up with something useful.

**Comment by Andereoo** [comment]
@maxim3007, I've made a couple of changes that should hopefully solve your issues.

Here's an interesting experiment to do. Check that the `noto color emoji` font is installed on your **Ubuntu** system. It should be installed by default. Then run this:
```
import tkinter as tk
root = tk.Tk()
tk.Label(root, text="test", font=("noto color emoji", "12", "normal")).pack()
root.mainloop()
```
If the `noto color emoji` font is installed properly, you'll probably see that Tkinter crashes. That's the main problem with `https://emojipedia.org/locked/` on Linux. The website uses the `noto color emoji` font, which crashes Tkinter.

On **Windows**, run:
```
import tkinter as tk
root = tk.Tk()
tk.Label(root, text="Emoji: 👏").pack()
root.mainloop()
```
Tkinter will likely also crash (on 32-bit Python anyway). The `https://emojipedia.org/locked/` website uses emojis such as the one in the example, which some Tcl versions on Windows don't seem to be able to handle. I assume that Tkinter on Mac also suffers from a similar issue.

Since these are Tkinter issues, I can't provide an actual fix, but I _can_ try to prevent them.

I've updated TkinterWeb. The new version removes all emojis above Tkinter's limit. It also uses regex to replace the `noto color emoji` font-family with `arial`. That means that most emojis will not be shown, but at least your app won't crash.

I've also noticed a Tkhtml3 bug that causes crashes on some other websites. If a website is using the `rgb()` function with invalid parameters, Tkhtml crashes. The latest TkinterWeb version only allows `rgb()` functions if they appear to be valid, preventing site crashes (eg. `color: rgb(somecolor)` <-- removed, `color: rgb(0,0,0)` <-- allowed).

These prevention tactics can be disabled by calling `frame.enable_crash_prevention(False)`, not that you'd exactly want to disable these extra measures.

Please let me know if you still encounter crashes after updating TkinterWeb or if this fixes your issues!

**Comment by maxim3007** [comment]
what encoding of request is used when loading html from website??

**Comment by Andereoo** [comment]
Hello!

Good point! I completely forgot about `load_html`! I'll fix that.

**Comment by maxim3007** [comment]
I've realized that on macOS when using `load_website` all emojis are shown but the bug is fixed!
How does it work ?!

**Comment by Andereoo** [comment]
I've fixed the bug with `load_html`. It should work now.

Regarding the text encoding, when loading a website, the HTML is decoded without any specific text encoding. The encoding is guessed by Python. If you want to force a specific text encoding use the `decode="encoding"` parameter (replacing `"encode"` with `"utf-8"` or any other text encoding.)

Regarding the emojis on MacOS, there are a couple of things that are be going on. For one, your link has both text emojis (which can cause crashes) and image emojis (which are perfectly safe). It's possible that you are seeing the images, but not the text emojis. Also, any emojis below Tcl's limit should be removed - many emojis are within Tcl's limit and will still be shown. In case you are curious, the algorithm used to strip unsupported characters is `html = ''.join(c for c in html if c <= u'\uFFFF')`.

**Comment by maxim3007** [comment]
Thank you very much !! 
Simple and useful algorithm by the way

**Comment by Andereoo** [comment]
No problem! Thanks again for letting me know about the bug.  And yes, the algorithm is a surprisingly simple solution.

As always, let me know if you find any other bugs!
