### ISSUE TITLE
Does TkHTML-3 support the CSS at-rule '@media'?

### ISSUE THREAD

**Issue by Zamy846692** [Andereoo/TkinterWeb#112]
Just wondering whether this project's backend supports it, it isn't mentioned in http://tkhtml.tcl.tk/support.html but the source code does reference it in https://github.com/Andereoo/TkinterWeb-Tkhtml/blob/main/src/cssparser.c#L922, however when I try to run [this](https://www.w3schools.com/cssref/tryit.php?filename=trycss3_media_bg) in .load_html it doesn't work - so I assume it isn't supposed to do anything?
Would appreciate your input here!

**Comment by Andereoo** [comment]
Hi!

Yes and no...while I haven't tried it, Thktml should support the CSS2 usage of @media. CSS2 allowed for different style rules for different media types (i.e. computer screens, printers, handheld devices, etc.) The print media type was generally the only one that got any use in the real world. CSS3 tried to fix this by introducing media queries (i.e. from your example `@media only screen and (max-width: 600px)`). Tkhtml doesn't support this, but you can mimic its behaviour through Python. 

For instance, you can get the screen width every time the app is resized by binding to the <Configure> event and use `add_css()` to manipulate the page if the screen is less than 600px wide. Just make sure you are only calling `add_css()` whenever the screen width changes from <600px to >600px, and not every time its size changes, which would cause a lag.

I hope this helps!

**Comment by Zamy846692** [comment]
Yeah.
I tried 
```
@media screen {
    body {background-color: lightblue;}
}
```
And it seems to work.

**Comment by Andereoo** [comment]
Yes, thanks for submitting the pull request! It's been very busy lately and will likely be a little while before I have time to look through it.
