### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by maxim3007** [Andereoo/TkinterWeb#16]
Hello!
I need to get coords (x,y) of some nodes in my app and I have their names e.g. `::tkhtml::node0`.
Is it possible to get node coords by name?? if yes, can you tell me how

**Comment by Andereoo** [comment]
Hello,

Yes, it is possible. I haven't created a function that does this, but you can still do it by interacting with Tkhtml itself.

You should be able to use `yourframe.html.tk.call(yourframe.html._w, "bbox", yournode)`. Assuming `yournode` exists, this will return a tuple with 4 integers. The first two are the x and y coordinates of the top-left corner of the node. The other two integers are the x and y coordinates of the bottom-right corner of the node. If the node is empty, an empty string will be returned, and if the node doesn't exist, an exception will be raised.

If you want me to expose this as a proper Python command, just let me know.

As always, feel free to let me know if you have any other questions!
