### ISSUE TITLE
Crash on windows 32-bit

### ISSUE THREAD

**Issue by maxim3007** [Andereoo/TkinterWeb#20]
Hi!

my app crashes exactly like in issue #1 ,

is it because pip missing Tkhtml.dll?

I hope you will fix it asap!

**Comment by maxim3007** [comment]
can't reproduce on win64

**Comment by Andereoo** [comment]
Hi!

Thank you very much for letting me know about this. Something must have gone wrong when I uploaded the last TkinterWeb version. I have re-compiled the 32-bit binaries and included them in the package. Consider reinstalling TkinterWeb, and let me know if it works.

**Comment by maxim3007** [comment]
Works for me!
Thanks!!!
