### ISSUE TITLE
Using base64 images

### ISSUE THREAD

**Issue by valtervg13** [Andereoo/TkinterWeb#23]
I'm working on a project that would require me to display base 64 images, loaded straight from the encoded data with no external files involved. I can generate the html and open it in another browser no problem, but attempting it on the htmlFrame object always yelds an error message. Is the format not supported?

The HTML tag that generates the error is:
`<img src="data:image/png;charset=utf-8;base64,{banner_img}">`
where `{banner_img}` is the encoded data.

Also, the error reads: "[base 64 data] could not be shown because it is corrupt or is not supported yet."

**Comment by Andereoo** [comment]
Hi @valtervg13,

Thank you for bringing this issue to my attention. TkinterWeb should support base64 encoded images. Can you please provide an reproducible example of the image causing the error? That way I will be able to try and troubleshoot the problem. 

Thanks!

**Comment by valtervg13** [comment]
Thanks for the quick response!

I did some testing while trying to make a simple example and found that the problem only arises with big, complex images.
Simple images like the github logo display normally.

I'm sendind a simplified code with the problematic image as an attachment since the encoded base 64 within is simply huge. The html file is generated by the code, but if the sise of the image string starts causing problems with the IDE it should b enough for testing the problem.
[Testing.zip](https://github.com/Andereoo/TkinterWeb/files/7597241/Testing.zip)

Thanks a bunch!

**Comment by Andereoo** [comment]
I'm getting the error 'Compressed (zipped) folder is invalid' when opening your file. Perhaps you could try uploading it again? Thanks!

**Comment by valtervg13** [comment]
Sure thing! It opens normally when i download it though.

Here it goes:
[Testing.zip](https://github.com/Andereoo/TkinterWeb/files/7602552/Testing.zip)

**Comment by valtervg13** [comment]
I found out the problem: i was using the wrong image extension in the html. Not a problem with the htmlFrame.

Thanks for your time and effort! Sorry for the blunder.

I will close the topic now and should probably delete it since it was an error on my part.

Thanks again!

**Comment by Andereoo** [comment]
No problem! Blunders happen sometimes; don't worry about it. I'm just glad that you have figured out your problem!
As always, never hesitate to reach out if something else isn't working quite right!
