### ISSUE TITLE
Sliders in control aren't rendered

### ISSUE THREAD

**Issue by manchuwook** [Andereoo/TkinterWeb#27]
When adding a slider input control, it only displays it as a Text box

````html
        <form action="index.html" method="POST">
            <div class="slidercontainer">
                <label for="wholeNotesWeight">Whole Notes</label>
                <input type="range" min="-1" max="1" value="0" step="0.0125" class="slider"
                       name="wholeNotesWeight" id="wholeNotesWeight">
            </div>
           <!-- More content -->
       </form>
````

![image](https://user-images.githubusercontent.com/431161/149844604-96721059-b049-4458-b95d-f693dbcec06b.png)

I really like being able to use TKinterWeb in Reaper, and I do appreciate your work in this!

**Comment by Andereoo** [comment]
Hello!

I have added support for HTML sliders. Try updating TkinterWeb to give it a try. Unfortunately, `ttk.Scale` doesn't support tick intervals, so the `step` parameter is not yet supported. Hopefully you can work around that. 

Let me know if this works for you, or if something needs to be changed!

**Comment by manchuwook** [comment]
It works for me!  Thank you for being so fast on this. 

![image](https://user-images.githubusercontent.com/431161/150003636-3e2cb6e9-d247-4a57-8380-734d3049f9f2.png)

**Comment by Andereoo** [comment]
No problem! Glad I could be of use here. As always, please do let me know if something isn't working right or to request some new features!
