### ISSUE TITLE
Can't open local file

### ISSUE THREAD

**Issue by asimard1** [Andereoo/TkinterWeb#29]
Trying to open a local file (url starting with file://localhost/...) doesn't work as http:// is added automatically.

**Comment by asimard1** [comment]
Sorry, I just found the load_file method. The file however does not load correctly. I will open another issue for this.

**Comment by Andereoo** [comment]
No worries! For the future, `load_website` is just a convenience method that will add 'http://' if the url doesn't start with 'https://' or 'http://'. `load_file` is basically the same thing, but for `file://` urls. You can use `load_url` to load a url of any kind (website, file, data url, etc.), but the url must begin with a proper url scheme (there is no url checking).

**Comment by Dawlat1** [comment]
I have the same problem while trying to load a local html in tkinter window using tkinter web and I still can’t solve it. My local html is in “E:\App\App\sys_con.html” and it can’t be found and loaded using load_file(“file://”).  
Can someone help with that?
