### ISSUE TITLE
Tkinter app crashes when I switch to the tab with HtmlFrame

### ISSUE THREAD

**Issue by Yilmaz4** [Andereoo/TkinterWeb#31]
Basically, when HtmlFrame is placed in a frame of a Notebook and you switch to that frame/tab right after the program starts, program crashes. I encountered this problem while adding HtmlFrame to Help & About tab of my program, and to make sure the problem is about the library and not my code, I've simplified the code:

```python
from tkinter import *
from tkinter.ttk import *

from tkinterweb import HtmlFrame
from markdown import markdown
from requests import get

root = Tk()

notebook = Notebook(root, height=400, width=400)

frame1 = Frame(notebook)
frame2 = Frame(notebook)
frame3 = Frame(notebook)

notebook.add(frame1, text="Frame 1")
notebook.add(frame2, text="Frame 2")
notebook.add(frame3, text="HtmlFrame")

request = get("https://raw.githubusercontent.com/Yilmaz4/Encrypt-n-Decrypt/main/README.md").text
HTML = markdown(request)
readmePage = HtmlFrame(frame3, messages_enabled=False, vertical_scrollbar=True)
readmePage.load_html(HTML)
readmePage.pack(fill=BOTH, expand=True)

label1 = Label(frame1, text="This is the first frame, switch to the third frame\nto crash the program", justify=CENTER)
label1.place(relx=0.5, rely=0.5, anchor=CENTER)

label2 = Label(frame2, text="This is the second frame, as you switched to this\nframe before the third frame, program will no longer crash.", justify=CENTER)
label2.place(relx=0.5, rely=0.5, anchor=CENTER)

notebook.pack(fill=BOTH, expand=True)

root.mainloop()
```

Note: you can install the markdown package with this command: `pip install markdown`

When you run the code, click on "HtmlFrame" tab. The program will crash. However, if you click on another tab than the tab with HtmlFrame, and then switch to the tab with HtmlFrame, the program doesn't crash.

I'm on Windows 11 build 22000.469 (21H2)

**Comment by Yilmaz4** [comment]
Nevermind, I read FAQ and saw that this was a known issue. I'm closing this.

**Comment by Andereoo** [comment]
No worries! Just let me know if you encounter any other issues.
