### ISSUE TITLE
Only white screen in the window

### ISSUE THREAD

**Issue by applicatlat** [Andereoo/TkinterWeb#32]
No information is visible on some websites. I tried https://www.instagram.com but I received this error:
Connecting to www.instagram.com.

Loading stylesheet from https://www.instagram.com/static/bundles/metro/ConsumerUICommons.css/a655099c07ef.css.

Loading stylesheet from https://www.instagram.com/static/bundles/metro/Consumer.css/d409f54d4a3d.css.

**Comment by Andereoo** [comment]
Please see #33.

As always, feel free to let me know if you notice any other anomalies or to suggest new features.

**Comment by applicatlat** [comment]
Thank you very much.

**Comment by Andereoo** [comment]
No problem! Sorry I couldn't be of more help here.
