### ISSUE TITLE
Can't find package Tkhtml

### ISSUE THREAD

**Issue by rodneyboyd** [Andereoo/TkinterWeb#36]
Hi 'Andereoo',

I've been using tkinterweb (thanks!) in a Python 3 application on Windows and ran up against a problem in the compiled version of my app. Context is that I compiled my .py code to .pyd files using Cython, then used py2exe to generate an executable. My setup options are as follows:

`setup(data_files=data_files,console=['picardy.py'], options={"py2exe" : {"includes" : ["inflect", "xml.dom", "xml.dom.minidom", "tkinter", "winsound"], 'packages': ['tkinterweb']}})`

py2exe executes successfully but when I try to run the app I see:

```
Traceback (most recent call last):
  File "tkinterweb\bindings.pyc", line 82, in __init__
  File "tkinterweb\utilities.pyc", line 657, in load_tkhtml
_tkinter.TclError: can't find package Tkhtml
```
Do you have any idea what may be going on? I thought Tkhtml would be something I could install with pip but that doesn't seem to be the case.

Btw when I run from the Python interpreter there is no problem.

Thanks and best regards,
Rodney

**Comment by Andereoo** [comment]
Hi Rodney,

I installed py2exe to test this out and can confirm that I get this error message too. It seems that py2exe is including _some_ of TkinterWeb's files but not _all_ of them. py2exe's package recognition is known to be a bit sketchy. I'm sure there's a way to work around this, but I don't really use py2exe  and can't come up with something easily. Would you be willing to use PyInstaller instead? 

Simply open command prompt, run `pip install pyinstaller` and then `cd` into Downloads or whatever directory you are working out of. Then run `pyinstaller yourfile.py --noconsole --collect-all tkinterweb` and you should be good.

Let me know if this works!

**Comment by rodneyboyd** [comment]
Hi, thanks for the quick response. 

It was **almost** as simple as you described :-) I had to include a few `--hidden-import` options in the pyinstaller command line to pick up various modules. After that the packaging finished and I could run my app without issues. 

Thanks again!
Rodney

**Comment by Andereoo** [comment]
Sounds good!
