### ISSUE TITLE
HtmlLabel does not handle background color

### ISSUE THREAD

**Issue by jsinger0420** [Andereoo/TkinterWeb#37]
Here is the HTML I'm trying to render using HtmlLabel...  It seems to work except the "background: #aa9cfc;" colors don't display.  You have to edit the post to see the html

<div class="entities" style="line-height: 2.5; direction: ltr">
<mark class="entity" style="background: #aa9cfc; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;">
    Albert Einstein
    <span style="font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem">PERSON</span>
</mark>
 was born in Ulm,[7] in 
<mark class="entity" style="background: #feca74; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;">
    the Kingdom of WÃ¼rttemberg
    <span style="font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem">GPE</span>
</mark>
 in 
<mark class="entity" style="background: #feca74; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;">
    the German Empire
    <span style="font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem">GPE</span>
</mark>
, on 
<mark class="entity" style="background: #bfe1d9; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;">
    14 March 1879
    <span style="font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem">DATE</span>
</mark>
 into a family of secular 
<mark class="entity" style="background: #c887fb; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;">
    Ashkenazi
    <span style="font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem">NORP</span>
</mark>
 Jews.</div>

**Comment by Andereoo** [comment]
Hi @jsinger0420, I can't seem to reproduce your issue; can you please post your sample code? Thanks!

**Comment by jsinger0420** [comment]
here is a script that I run using Idle.

from tkinterweb import HtmlLabel
try:
  import tkinter as tk #python3
except ImportError:
  import Tkinter as tk #python2

sentence = '''<div class="entities" style="line-height: 2.5; direction: ltr"><mark class="entity" style="background: #aa9cfc; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;">
    Albert Einstein
    <span style="font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem">PERSON</span>
</mark>
 was born in Ulm,[7] in 
<mark class="entity" style="background: #feca74; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;">
    the Kingdom of WÃ¼rttemberg
    <span style="font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem">GPE</span>
</mark>
 in 
<mark class="entity" style="background: #feca74; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;">
    the German Empire
    <span style="font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem">GPE</span>
</mark>
, on 
<mark class="entity" style="background: #bfe1d9; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;">
    14 March 1879
    <span style="font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem">DATE</span>
</mark>
 into a family of secular 
<mark class="entity" style="background: #c887fb; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;">
    Ashkenazi
    <span style="font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem">NORP</span>
</mark>
 Jews.</div>'''
 
root = tk.Tk()
frame = HtmlLabel(root)
frame.load_html(sentence)
frame.pack(fill="both", expand=True)
root.mainloop()

**Comment by jsinger0420** [comment]
That works but it puts the background color on the entire sentence.  Here are some screenshots so you can see what should happen.

Also, thanks for helping out on this…  😊

I’ve attached an html file that renders like the below screen shot in chrome.  Notice how the different phrases in the sentence have different background colors.
***@***.***

Now I put the same html in the python script (that I also attached) and it renders like this…  Notice that it bolded the word “PERSON” but it didn’t do the yellow background on “Albert Einstein  PERSON”.

***@***.***

**Comment by Andereoo** [comment]
It seems like Tkhtml is having issues with the `<mark>` element. I'll look into this, but for now you can replace `<mark>` with `<span>` and you should be good!

**Comment by jsinger0420** [comment]
Ok I’ll give it a try and let you know the results.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jsinger0420** [comment]
I changed the “mark” to “span” elements and  that seems to work.  Unfortunately, I’m using html generated by another app (spacy) so it would be best if you could support the Mark html tag.  I hope you fix this in the future.  I’ll go ahead and hack the html after its generated but it’s not a good long term solution.

Anyway I appreciate you sticking with this – your library is really needed for Tkinter and python as there does not seem to be any other solution.

**Comment by Andereoo** [comment]
Some updates...

Tkhtml, the HTML/CSS parser that this project is based on, supports HTML 4.01. `<mark>` is an HTML 5 element, so is not supported. I could add support for `<mark>` elements, but then I would have to recompile Tkhtml for all devices, which would be burdensome.

I switched the Tkhtml parser mode so that it does not ignore unknown tags. This means that all unsupported tags, such as `<mark>` will not be ignored and therefore can be themed. While this change also makes the parser less careful about other non-HTML code (and essentially makes it an XML viewer), in practice I have not found any issues. Regardless, it can be reverted by `frame.set_parsemode("html")`. 

This should fix your problem. Consider updating TkinterWeb and let me know if it works!

**Comment by Andereoo** [comment]
@jsinger0420 Can you confirm that this issue has been resolved on your end?

**Comment by jsinger0420** [comment]
Sorry, I got busy and forgot to finish this.  Go ahead and mark it resolved.  Thanks for your diligence on this.  I’ll email you when I post the code that uses your library.  I’m working with the spaCy NLP library and needed your code to display the spaCy sentence diagram.

**Comment by Andereoo** [comment]
Sounds good! Can't wait to try out your code when it's done!
