### ISSUE TITLE
Charset ?

### ISSUE THREAD

**Issue by metal3d** [Andereoo/TkinterWeb#4]
Hello,

Very impressed by this package, is there any way to manage the charset ?

My content is in french, and there are problems with accentuated chars for example...
![image](https://user-images.githubusercontent.com/100080/112974898-4623da80-9153-11eb-809a-52d5731ae193.png)

Note that I include the `<meta charset="utf-8">`.

Thanks  a lot !

**Comment by metal3d** [comment]
Note: this workes as expected:

```
content = requests.get(
    "https://www.metal3d.org/blog/2020/d%C3%A9mystifier-python-async/"
)

html.add_html(content.content.decode("utf-8"))
```

![image](https://user-images.githubusercontent.com/100080/112991029-fcdd8600-9166-11eb-95bb-4be08cba28a3.png)

**Comment by Andereoo** [comment]
Hi @metal3d,

Thank you for letting me know about this. 

TkinterWeb uses the `requests` package, which automatically determines the encoding of websites. Sometimes it makes mistakes, though. I can't reproduce this issue on my end, but I will include an option to set the text encoding in the next release. 

You could also check that you are using the most up-to-date versions of TkinterWeb and requests - this may fix your issue.

**Comment by metal3d** [comment]
Hi, I made updates yesterday in a virtualenv (pipenv), and the problem is still here. But that's not a blocking problem as I can decode myself :) 
That will be better when the option will be present.

**Comment by Andereoo** [comment]
Hi @metal3d,

I have a quick question. Do you have any issues with accented characters when you use the code below?

```
with urlopen(Request("https://www.metal3d.org/blog/2020/d%C3%A9mystifier-python-async/")) as handle:
    content = handle.read().decode()
html.add_html(content)
```

**Comment by metal3d** [comment]
I can't use this snippet without to know from wich package you take Request and urlopen 😄 

`urlopen` from `urllib` doesn't take `Request` object (only string)
`Request` comes from the `requests` package ? In this case, why not using `requests.get()`  like in my example ?

**Comment by metal3d** [comment]
It is ok for me:
![image](https://user-images.githubusercontent.com/100080/113246922-412d6b00-92ba-11eb-859d-13a1a9e3ec7e.png)

**Comment by Andereoo** [comment]
I have updated this package.  Updating your version should fix this issue. 

The update will fix any issues you may have with garbled charachters, but if you do decide that you still want to manually set the charset, use `decode='[your decoding]'` when calling `load_website`, `load_file` or `load_url`. For example, to force the decoding to ISO, you could run `html.load_website("https://www.metal3d.org/blog/2020/d%C3%A9mystifier-python-async/", decode="ISO 8859-1")`. Keep in mind that certain encodings may raise errors on some websites.
