### ISSUE TITLE
Vertical expanding/centering?

### ISSUE THREAD

**Issue by michezio** [Andereoo/TkinterWeb#41]
I'm no expert of HTML/CSS but I'm trying to make a div and center it in the screen filling 80% of the space horizontally and vertically.

This is a simplified demo of what I'm trying to obtain:

```python
import tkinter as tk
from tkinterweb import HtmlFrame

html = \
"""
<!doctype html>
<html>
<body>
    <div class="center-red">
    TEST
    </div>
</body>
</html>
<style>
body {
    width: 100vw;
    height: 100vh;
}
.center-red {
    width: 80%;
    height: 80%;
    margin: auto;
    padding: 10px 10px;
    background-color: red;
    font-size: 100px;
    color: white;
}
</style>
"""


root = tk.Tk()
root.title("TEST")

root.geometry("%dx%d+%d+%d" % (800, 600, 100, 100))

html_frame = HtmlFrame(root, messages_enabled=False)
html_frame.pack(fill="both", expand=True)

html_frame.load_html(html)

root.mainloop()
```

And this is the output:

![Screenshot (69)](https://user-images.githubusercontent.com/33634641/186957365-5ec2ecfe-ec39-4ed3-8123-fadd9f71de78.png)

Why is the div not expanding vertically? I tried to set a fixed height to `body` and the div expands correctly, but by setting body with `height: 100vh` or `height: 100%` it doesn't work. It's like it fails to get the window height to expand the body (?). I tried the same in Chrome and it works correctly. 

Also, since I'm here, how am I supposed to center the div vertically the same way it happens horizontally with `margin: auto`?

**Comment by Andereoo** [comment]
Hi!

Tkhtml, the rendering engine TkinterWeb is based on, doesn't seem to be able to make any elements other than the body fill the entire screen. It may very well be that Tkhtml fails to get the window height to expand the body. Unfortunately, fixing this is outside the bounds of this project. However, you can use some extra code to force it to expand to the screen height. Something like this should work:

```
def resize(*args, **kwargs):
    height = root.winfo_height()
    html_frame.html.parse_css(data="yourelementheight: %spx};" % height)

root.bind("<Configure>", resize)
```
This would get the window height anytime it resizes and adjust the element `yourelement` to match the height.

Regarding you question about vertical centering, this can be a little tricky to get right, but the easiest with TkinterWeb might be to use a table. However, due to some other limitations with Tkhtml, it is a little difficult to incorporate this into your code, where the content has to be 80% of the screen height. The easiest way that I've found to work around this is to calculate and set the height of `center-red` manually, rather than setting `height: 80%`. Here's a modified version of your code that (I think?) should do what you are looking for. It's not pretty, but hey, it works!

```
import tkinter as tk
from tkinterweb import HtmlFrame

html = \
"""
<!doctype html>
<html>
<body>
<table>
<tr class="content">
<td class="cell">
<div class="center-red">TEST</div>
</td>
</tr>
</body>
</html>
<style>
body {
    padding: 0px;
    margin: 0px;
}
table {
    width: 80%;
    margin: auto;
}
.cell {
    vertical-align: middle;
}
.center-red {
    padding: 10px 10px;
    background-color: red;
    font-size: 100px;
    color: white;
}
</style>
"""

center_red_percentage = 80

root = tk.Tk()
root.title("TEST")

root.geometry("%dx%d+%d+%d" % (800, 600, 100, 100))

html_frame = HtmlFrame(root, messages_enabled=False)
html_frame.pack(fill="both", expand=True)

def resize(*args, **kwargs):
    height = root.winfo_height()
    
    html_frame.html.parse_css(data=".content{height: %spx};" % height)
    html_frame.html.parse_css(data=".center-red{height: %spx};" % str((int(height)/100)*80))

root.bind("<Configure>", resize)
html_frame.load_html(html)

root.mainloop()

```

Let me know if this helps!

**Comment by michezio** [comment]
Hi @Andereoo, thank you so much for spending your time to help me, really appreciate it!

Your example works perfectly fine, but you have to know a-priori the class name for the div you want to be centered (in this case `center-red`) so that you can use it in the callback. Also, width/height percentages are defined in the Python code and not in the HTML code. These may not be ideal in a more general context.

In my main application, for example, I am receiving the HTML code from an API and the class name is not known beforehand, and width/height percentages can change and have to be defined in the HTML code I receive.

I've been fiddling with your example and I realized that actually the `resize` callback can add a CSS just for the body, expanding it to the whole canvas. This way percentages for a child `div` inside `body` work exactly as they should.

Also, by putting `position: relative` into `body` and `position: absolute` inside the `div`, I can achieve the expanding/centering this way:

```python
import tkinter as tk
from tkinterweb import HtmlFrame

html = \
"""
<!doctype html>
<html>
<body>
    <div class="center-red">
    TEST
    </div>
</body>
</html>
<style>
.center-red {
    position: absolute;
    width: 80%;
    height: 60%;
    left: 10%;
    top: 20%;
    background-color: red;
    font-size: 100px;
    color: white;
}
</style>
"""

root = tk.Tk()
root.title("TEST")

root.geometry("%dx%d+%d+%d" % (800, 600, 100, 100))

html_frame = HtmlFrame(root, messages_enabled=False)
html_frame.pack(fill="both", expand=True)

def resize(*args, **kwargs):
    width = root.winfo_width()
    height = root.winfo_height()

    html_frame.add_css(f"body {{ position: relative; margin: 0; width: {width}px; height: {height}px; }}")

root.bind("<Configure>", resize)

html_frame.load_html(html)

root.mainloop()
```

**Comment by michezio** [comment]
I was fiddling some more and I found out that you can expand the `body` to the whole screen using just the HTML code by applying the same CSS to the `html` tag too, so no need for the callback:

```python
import tkinter as tk
from tkinterweb import HtmlFrame

html = \
"""
<!doctype html>
<html>
<body>
    <div class="center-red">
    TEST
    </div>
</body>
</html>
<style>
html, body {
    position: relative;
    margin: 0;
    width: 100%;
    height: 100%;
}
.center-red {
    position: absolute;
    width: 80%;
    height: 60%;
    left: 10%;
    top: 20%;
    background-color: red;
    font-size: 100px;
    color: white;
}
</style>
"""

root = tk.Tk()
root.title("TEST")

root.geometry("%dx%d+%d+%d" % (800, 600, 100, 100))

html_frame = HtmlFrame(root, messages_enabled=True, vertical_scrollbar=False, horizontal_scrollbar=False)
html_frame.pack(fill="both", expand=True)

html_frame.load_html(html)

root.mainloop()
```

Now, since it's something that in my particular application I need to do for each HTML I receive, I can always add the CSS portion relative to `html` and `body` after the `load_html` method so that the API doesn't have to include that in the HTML code:

```python
import tkinter as tk
from tkinterweb import HtmlFrame

html = \
"""
<!doctype html>
<html>
<body>
    <div class="center-red">
    TEST
    </div>
</body>
</html>
<style>
.center-red {
    position: absolute;
    width: 80%;
    height: 60%;
    left: 10%;
    top: 20%;
    background-color: red;
    font-size: 100px;
    color: white;
}
</style>
"""

root = tk.Tk()
root.title("TEST")

root.geometry("%dx%d+%d+%d" % (800, 600, 100, 100))

html_frame = HtmlFrame(root, messages_enabled=False)
html_frame.pack(fill="both", expand=True)

html_frame.load_html(html)
html_frame.add_css("html, body { position: relative; margin: 0; width: 100%; height: 100%; }")

root.mainloop()
```

**Comment by Andereoo** [comment]
That's great! Your example works perfectly. I hadn't thought to use absolute positioning, but that's a lot simpler. 

If I remove the `add_css` line and instead add the CSS to the HTML code at the top, it also seems to work. Try the code below, and let me know if it works for you too.

```
import tkinter as tk
from tkinterweb import HtmlFrame

html = \
"""
<!doctype html>
<html>
<body>
    <div class="center-red">
    TEST
    </div>
</body>
</html>
<style>
html, body {
    position: relative;
    margin: 0;
    width: 100%;
    height: 100%;
}
.center-red {
    position: absolute;
    width: 80%;
    height: 60%;
    left: 10%;
    top: 20%;
    background-color: red;
    font-size: 100px;
    color: white;
}
</style>
"""

root = tk.Tk()
root.title("TEST")

root.geometry("%dx%d+%d+%d" % (800, 600, 100, 100))

html_frame = HtmlFrame(root, messages_enabled=False)
html_frame.pack(fill="both", expand=True)

html_frame.load_html(html)

root.mainloop()
```

**Comment by Andereoo** [comment]
It's similar but not quite the same. I removed `html_frame.add_css("html, body { position: relative; margin: 0; width: 100%; height: 100%; }")` and instead added that CSS with the rest of your HTML code.

**Comment by michezio** [comment]
And that's exactly what is in my comment too :D
I proposed two version of the code, one with the CSS inside the HTML and the other with the CSS added with `add_css` method.
