### ISSUE TITLE
Is there any "dark mode" for the frame? 

### ISSUE THREAD

**Issue by Viswas-Programs** [Andereoo/TkinterWeb#42]
Like many apps now, dark mode is essentially everywhere. Is there any way to implement a forced dark mode for websites through your HTMLFrame widget in any way?
PS: I saw your HTMLFrame documentation too, no mentions about themes at all, so I ask this question. 

And also, good initiative too! In spite of this being a "lightweight" web viewer, I am actually trying to create a full blown browser in python with this! Keep going with this bro :)

**Comment by Andereoo** [comment]
Hi! 

It is possible to use `add_css` to manually set custom CSS into the frame after the site loads in order to modify the site or change the theme. However, it sounds like you are looking for a built-in option to automatically translate all document colours to a dark theme. 

TkinterWeb does not have this functionality. Honestly, it's a great idea but I never thought to implement it. I'll see what I can do!

**Comment by Viswas-Programs** [comment]
Any possible updates on this issue @Andereoo?

**Comment by Andereoo** [comment]
Hi! 

Some updates...

I've added a basic dark theme. You can toggle it via `yourhtmlframe.enable_dark_theme(True, True)` .
- The first `True` will allow the dark theme for the document. When enabled, a regular expression will scan stylesheets prior to loading and detect colours. Any light background colours and dark foreground colours will then be inverted, making a 'dark mode' effect.
- The second `True` will cause images to also be inverted.

This is pretty preliminary and causes some websites to hang, but it seems to work decently. I'll look into some future improvements, and feedback is certainly welcome. Once I can solve the compatibility issues some other users are pointing out, I'll look into a way to manipulate colours without directly scanning stylesheets, which has some performance impacts.

Try updating TkinterWeb and let me know what you think!

**Comment by Viswas-Programs** [comment]
Yeah It's great! Working good for me
Here are the results from my web browser (like MY webbrowser)
![image](https://user-images.githubusercontent.com/115633223/209457317-75613e06-c486-408e-a420-bd78b1bb91ae.png)
![image](https://user-images.githubusercontent.com/115633223/209457320-c975e0a8-03be-4997-ad1b-24b15506db3e.png)
As you can see, it does make the images look abominal, but I will change the second bool to false to fix this, not a hard thing to do, You can improve it more though, good try bro.

**Comment by Viswas-Programs** [comment]
A followup on the previous comment: I tried some more websites other than google. like normal links, and some of them take so long to respond or outright crash out. this IS an issue still. good try again.

**Comment by Viswas-Programs** [comment]
Hello bro, an update on this method, this does crash on some websites and consumes a lot of memory. 
And also, this looks a bit ugly with pictures, so enabling that makes images look bad, but disabling it makes all the pictures normal and some pictures are in white background and inconsistent.
I hope you have time to fix this issue then.
Still great try though.
