### ISSUE TITLE
Frame.on_link_click method doesn't work!

### ISSUE THREAD

**Issue by Viswas-Programs** [Andereoo/TkinterWeb#43]
Hi again, I am trying to use the on_link_click method to capture the link clicks, and I designed the function to load the url when called, but it's not working as I excepted! 
It just prints out "A link to blahblahblah has been clicked" and nothing happens then.
this is my function handling the url click. (Never mind the nonlocals and the vars, this is straight from my program.
`
def addToList(url):
        nonlocal searches
        nonlocal searchNo
        searches.append(str(url))
        searchNo += 1
        text.delete()
        text.insert(0, url)
        frame.load_url(url)
`

as you can clearly, see, in the function called by the on_link_click method, I load a url in the frame, but, the output is this!

![image](https://user-images.githubusercontent.com/115633223/207909592-a7c5f3e8-15f1-4c16-bd2a-0702a37f5e12.png)

**Comment by Andereoo** [comment]
I can't seem to reproduce this error on my end. Could you please upload sample code for me to test? Thanks!

**Comment by Viswas-Programs** [comment]
Hello bro, sorry for late reply, I found out that the method works, the code fails to do it when I add the textbox changing code, which doesn't allow the code to run after that.
Your method works well, I like that, it's just that the tkinter Entry code, is causing that issue, I will close it, but just wanted to say something.
when I use the tkinter Entry code, like when updating text in an Entry widget in tkinter, then that produces that result, and not loading up the code, but if I comment that out OR remove it, it works. IDK why?

**Comment by Andereoo** [comment]
No worries! Glad it works now. FYI, if you are looking to set the content of your browser's urlbar when a link is clicked, it is best to use `on_url_change` instead of `on_link_click` because urls often redirect (eg. `randomsite.com` might automatically redirect to `https://www.randomsite.com/home`). That way, any changes to the url (including both link clicks and redirects) will automatically update in your urlbar.
