### ISSUE TITLE
Scroll Down Programmatically?

### ISSUE THREAD

**Issue by AaronCatolico** [Andereoo/TkinterWeb#44]
Is there a way to scroll down programmatically or without dragging the scrollbar down?

**Comment by Andereoo** [comment]
Hi! 

Yes, you can call `yourhtmlframe.html.yview_scroll(value, "units")`. The document will scroll down if `value` is positive and scroll up if negative. To move directly to a particular point on the page (i.e. scroll relative to the top of the document, and not the current position), instead use `yourhtmlframe.html.yview_moveto(value)`.

**Comment by AaronCatolico** [comment]
> Hi!
> 
> Yes, you can call `yourhtmlframe.html.yview_scroll(value, "units")`. The document will scroll down if `value` is positive and scroll up if negative. To move directly to a particular point on the page (i.e. scroll relative to the top of the document, and not the current position), instead use `yourhtmlframe.html.yview_moveto(value)`.

Thank you for the info! Also, the reason that I've discovered your module is because I don't really like the Ttk "Treeview" because it is too limited as far as adding images & styling it goes. So I have another question...

Say that I use your browser to created a HTML table with css to style it, do you think it would be okay to use it to load possibly 2,000-3,000 rows or do you think that it would be too slow to replace the Treeview widget?

I'd prefer to use your browser because I'd get way better aesthetically-speaking. The table would have to keep appending/loading additional rows to it.

Do you think that this could work out or be too resource heavy? It would have to be fast enough to keep appending new rows on the table. Thanks again for your share & great work 👍👍
