### ISSUE TITLE
Appending/Adding Additional HTML to a HTML Table Row

### ISSUE THREAD

**Issue by AaronCatolico** [Andereoo/TkinterWeb#45]
I'm trying to figure out a way to append additional rows to a html table without having to keep reloading the page without using 'load_html' to keep reloading the document and slowing down the browser while adding new table row data.

I see that there is the option to add additional html to the document without reloading it by using 'add_html', but how would I keep appending new rows to a html table?

For example, here's what my table rows look like:

```
<html>
	<table>
		<tr>
		      <th>#</h1><th>Heading 1</h1><th>Heading 2</h1><th>Heading 3</h1>
		</tr>
		<tr>
		      <td>1</td><td>DATA 1</td><td>DATA 1</td><td>DATA 1</td>
		</tr>
		**<!--APPEND/ADD-NEW-ROW-HERE!-->**
	</table>
</html>
```

Is there a way to quickly append another table row without constantly reloading the whole document? Is there a way just to manipulate the `'<tr>'` element so that I don't have to keep reloading the whole document?

I would like to click a Tkinter button, then it would append another row to the html table. Just trying to figure out which way it would be best to do so. I've tried replacing a 'html' variable where it says '', but it seems as though I'd have to keep reloading the document in order to replace the html variable that I'm using to load my html.

I'd appreciate the ideas. Thanks.

**Comment by Andereoo** [comment]
Hi!

Yes, there are many ways to get that done. I would use `add_html` to add a new table with the rows you want to add. I would then use `html.search` to get the two tables, `html.get_node_children` and `html.insert_node` to move the contents of the new table into the main table, and `html.delete_node` to delete the empty table. Here's an example:

```
import tkinter as tk
from tkinterweb import HtmlFrame

root = tk.Tk()
frame = HtmlFrame(root, messages_enabled=False)
frame.load_html("""
<table id="master-table">
      <tr>
            <th>#</h1><th>Heading 1</h1><th>Heading 2</h1><th>Heading 3</h1>
      </tr>
      <tr>
            <td>1</td><td>DATA 1</td><td>DATA 1</td><td>DATA 1</td>
      </tr>
</table>
""")

frame.pack(expand=True, fill="both")

frame.add_html("""
<table id="new-table">
<tr>
  <td>1</td><td>DATA 1</td><td>DATA 1</td><td>DATA 1</td>
</tr>
<tr>
  <td>1</td><td>DATA 1</td><td>DATA 1</td><td>DATA 1</td>
</tr>
<tr>
  <td>1</td><td>DATA 1</td><td>DATA 1</td><td>DATA 1</td>
</tr>
</table>
""")
master_table = frame.html.search("#master-table")
new_table = frame.html.search("#new-table")
new_rows = frame.html.get_node_children(new_table)

frame.html.insert_node(master_table, new_rows)
frame.html.delete_node(new_table)

root.mainloop()

```

Make sure that you are using the latest version of TkinterWeb.

Hope this helps!

**Comment by AaronCatolico** [comment]
Thank you for your support Anderoo.

Also, this leads me to a couple of new questions:

1. After testing your code, I keep getting the error message:
'self.frame.html.insert_node(self.master_table, self.new_rows)
AttributeError: 'TkinterWeb' object has no attribute 'insert_node''

Is this the proper way to insert a new node or was there some mistake in your example?

2. Say that I need to build a table that will have well over 1,000+ rows, is there a way to ensure the quickest loading? What do you think would ensure that I'd be able to load well over 1,000+ rows into a table without having any lag??? I will be using mult-threading to populate the table with new rows, but would still like to ensure optimal performance while do so. 

Thanks again for your support!

**Comment by Andereoo** [comment]
For the first question, you'll need to update TkinterWeb (eg. `pip install --upgrade tkinterweb`). I added the `insert_node` and `delete_node` functions earlier today to make it easier to access some underlying functions.

For the second question, I just tried generating a couple thousand rows and adding it to the table within a thread, and I don't experience any lag. I would recommend that you make sure that you are generating your rows within a thread and see what happens. If performance becomes an issue, just let me know and we can work it out!

**Comment by AaronCatolico** [comment]
I have tried it your way with the child nodes and deleting the new table, but it still lags after adding anywhere from 5,000 - 10,000 rows.

Try this code and you will see what I mean when you try to resize/drag the window or when hovering hovering over the table rows:

`       self.frame = HtmlFrame(self, messages_enabled=False)

        self.css = """
        table{position:relative; margin:auto; border:2px solid black; width:98%; margin-top:20px; margin-bottom:20px;}
        th{border-bottom:1px solid black; background-color:#333333; color:white;}
        tr:hover{background-color:gold; color:black; cursor:pointer;}
        td{border:1px solid black;}
        """

        self.html = """
        <table id="master-table">
              <tr>
                  <th>#</h1><th>Heading 1</h1><th>Heading 2</h1><th>Heading 3</h1>
              </tr>
              
        </table>"""


        self.frame.load_html(self.html)

        self.frame.add_css(self.css)
        self.frame.pack(expand=True, fill="both", pady=(0, 20))

        self.b = Button(self, text='START', bg='green', fg='white', cursor='hand2', command=self.add_rows)
        self.b.pack(pady=(0, 20))



    def add_rows(self):

        for i in range(1, 10001):
            self.new_html = """
                  <tr>
                      <td>""" + str(i) + """</td> <td>""" + str(i) + """</td> <td>""" + str(i) + """</td> <td>""" + str(i) + """</td>
                  </tr>
                  """

            self.html = self.html.replace('', self.new_html)


        self.frame.load_html('')
        self.frame.load_html(self.html)
        self.frame.add_css(self.css)`

**Comment by Andereoo** [comment]
Hi! I see what you mean. I tried stripping TkinterWeb down to the bare HTML engine it runs on and I still see the lagging. I don't think there is anything I can do about this, but I will still certainly keep an eye out for ideas. Are you sure you need that many rows? As a suggestion, most people wouldn't like having to scroll through 10,000 rows. I might either find a way to hide most of the rows and put in some filters or condense the information. Otherwise, if the lagging is too much, you might have to stick with the built-in Tkinter/TTK widgets. Keep in mind that you can always embed a Tkinter widget (eg. ttk.Treeview) _inside_ the HtmlFrame.
