### ISSUE TITLE
Segmentation fault: 11, Kernel Crash (Occasionally Worked) MacOS ARM64

### ISSUE THREAD

**Issue by dhruvjatkar** [Andereoo/TkinterWeb#47]
Hello,

Just wanted to see if this project was tested on MacOS with arm architecture? Even the simple demo only occasionally works (and quite randomly) for me, so just wanted to see if this was the problem or if it was something else. I get a "Segmentation fault: 11" error. Edited: I tried on Python version 3.7 and 3.8, and the latest tkinterweb version. Apologies if I am understanding any of these things incorrectly, I am still learning how to use these tools. Thank you!

**Comment by dhruvjatkar** [comment]
Update: also tried on an intel-based Mac, still had the same problem unfortunately.

**Comment by Andereoo** [comment]
Hi! Thanks for letting me know about this. MacOS has not been tested much. Tkinterweb is based on the Tkhtml html engine, which is largely written in C. This means that it has to be compiled for each OS and architecture. I'm looking into a way to remotely compile for and test on Macs, but it will take a while. In the meantime, if you would like, you can try following the instructions in https://github.com/Andereoo/TkinterWeb/issues/26 on compiling for Mac yourself.

**Comment by Andereoo** [comment]
Hi @dhruvjatkar, bug #26 has been resolved. Please upgrade TkinterWeb and let me know if this fixes the issue!
