### ISSUE TITLE
background ? width and height ?

### ISSUE THREAD

**Issue by metal3d** [Andereoo/TkinterWeb#5]
Hi again,

I continue my tests, and there is some stuff that I don't understand.

In the documentation, you say that HtmlFrame can take Frame arguments. I tried to set up background, width, and height. There is no error but the arguments seem to be not used (remove vertical scroll and message is OK).

For example, in a grid, the Frame takes a huge size.

Is there any way to scale the Frame to the content? (for the background, I will injet CSS)

**Comment by metal3d** [comment]
In http://tkhtml.tcl.tk/tkhtml.html, there is a "shrink" option that is not supported by tkinterweb actually

**Comment by Andereoo** [comment]
Hi @metal3d,

The HtmlFrame widget takes ttk.Frame arguments. It behaves as a ttk.Frame. Therefore, if you pass height and width to it, these arguments will be used _unless_ overridden by the geometry manager. 

For example, if you use `frame.pack(expand=True, fill="both")`, the frame's width and height will be overridden, and the width and height will be ignored. This is because in this case, the frame is being told to expand when possible, and so the widget's height and width are ignored. Meanwhile, if `frame.pack()` is used, the width and height will be used. 

You may want to check that your code is not overriding the width and height attributes of the HtmlFrame.

Regarding the `shrink` option, not all of the options from http://tkhtml.tcl.tk/tkhtml.html are exposed by the HtmlFrame. If you think you may benefit from using certain options, let me know and I will include them in the next update.

**Comment by metal3d** [comment]
I'm sure that I don't override the width and height. There are several issues with it actually:

- When I put the HtmlFrame in a grid, it expand height and width, while a Frame do not do this
- When I put htmlFrame in a Scrollable view (because I need to display something else above) and remove the vertical scrollbar of the htmlFrame, so the htmlFrame still scroll with mouse and doesn't expand

I will create some example to explain the problems.

**Comment by metal3d** [comment]
This example show that the HtmlFrame is expanding to a unwanted size
```python

from tkinter import Tk
from tkinter.ttk import Frame, Label

from tkinterweb import HtmlFrame


class App(Tk):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # with html frame
        html = HtmlFrame(self)
        html.add_html("<p>Hello !!!</p>")
        html.grid(row=0, column=0)

        label = Label(self, text="The label here")
        label.grid(row=0, column=1)

        # with simple frame
        simple = Frame(self)
        internlabel = Label(simple, text="Inside the Frame")
        internlabel.pack(fill="both", expand=1)
        simple.grid(row=1, column=0)

        Label(self, text="And the label2 on the right").grid(row=1, column=1)

App().mainloop()
```
![image](https://user-images.githubusercontent.com/100080/113174939-2ec81880-924b-11eb-9282-d9da336920c6.png)

**Comment by metal3d** [comment]
For the scrollbar problem, I'll need more code and it's in my second computer, I will propose here an example (but in short, removing the vertical scrollbar doesn't expand the frame if this frame is in a scrolled canvas with others elements)

**Comment by Andereoo** [comment]
Hi @metal3d,

Try using `html.grid_propagate(0)`. This tells Tkinter to honor the set width and height of the widget.

**Comment by metal3d** [comment]
Yes, by settings the width and height manually it's ok, but I want to make my view "responsive". And that means that I need to calculate the needed height (I will display several html elements)

To explain, that's what I do:
![e192ca63fbcba27b](https://user-images.githubusercontent.com/100080/113202547-28e22f80-926b-11eb-92fd-48424d38c6f3.png)

Here, there is no HTMLFrame, it's built with Labels, Styles and grids.

Each RSS view are, at this time, built with Labels where the text is treated to remove tags + manage event to react on click.
The image is also a Label (it's the "media" tag of the RSS item),
Everything is in a Grid.

I want to replace this by TkinterWeb to be able to display HTML contents. At this time, if I use it, I've got several problems. The first one is the problem with the height that is not calculated ;)

**Comment by metal3d** [comment]
And here is the second problem (see my example in tgz file)
Here I use a scrollable view with One label, and one HtmlFrame injected in the ScrollableFrame "internal frame".

The scrollbar of HtmlFrame is "hidden", but:
- mouse wheel still want to scroll the content of HtmlFrame
- my mouse wheel event scroll my view
- and so there are weird behaviors...

This is mainly because I don't have any chance to force HtmlFrame to have the "full html content size".


![ezgif-2-6c81df9d33ad](https://user-images.githubusercontent.com/100080/113205232-55e41180-926e-11eb-98d1-147c374ea552.png)

https://send.bitwarden.com/#Ce3z3cS7J0-QdKz8AU3_gw/LpXgRKMYs3HJLmuniF0SmA => the example program is here in tgz format

**Comment by Andereoo** [comment]
Hello @metal3d,

Thanks for posting the example. I think I see what the issue is. Before I post a solution, I'd like to know something. Do you want the label to stay on top of the HtmlFrame at all times, even while scrolling, or do you want it to go out of view when the frame is scrolled down?  

Nice UI by the way :)

**Comment by metal3d** [comment]
I want the label to be scrolled up. Look at my first example (the modern UI), The title and introduction text are on top of each RSS items. When I will scroll, I want the entire content to be scrolled (that's my scroll view).
Each RSS item will be a "HtmlFrame" that should not scroll internally, this is my application which manages the scroll.

This is the current behavior (it's a APNG file, I hope you see the animation):
![example-scroll](https://user-images.githubusercontent.com/100080/113245409-2efdfd80-92b7-11eb-8a48-96bf61376796.png)


And the wireframe
![image](https://user-images.githubusercontent.com/100080/113245375-1e4d8780-92b7-11eb-920b-6fa5d235467c.png)

**Comment by metal3d** [comment]
To be precise, I'm not interested by the fact that HtmlFrame can load a website 😄 - what is very interesting for me is that we can use HTML to display rich text, images and links. I will always deactivate the scrollbars. I only need that it works 'like a label" but with HTML content inside.

And to be honest, writing `HtmlLabel(master, text="<p>...</p>")` would be cool :)

I mean, instead of using HtmlFrame, a HtmlLabel could be what I really need.

**Comment by metal3d** [comment]
To complete the "expected behavior". This is what I can do with the https://github.com/paolo-gurisatti/tk_html_widgets package:
![image](https://user-images.githubusercontent.com/100080/113250111-278f2200-92c0-11eb-9037-bb1bbb5c8d30.png)

The HtmlLabel are white bordered

**Comment by Andereoo** [comment]
So you are looking for a HtmlLabel-like widget that 
    a) has no scrollbars (done)
    b) does not scroll on its own - you are going to handle that yourself
    c) expands to fit the content instead of hiding the content
Is that right? I have the next TkinterWeb release nearly ready, so I'll gladly add that functionality if that is what you are looking for. 

Regarding ImageTk, I am in the process of removing it. I have already removed dependency on `requests` in the upcoming release. It also has better CSS parsing. Regarding the CSS issues, this package runs off of a lightweight and fast - but discontinued HTML widget. It does a pretty good job parsing CSS from before it was discontinued, but cannot parse CSS introduced later. More 'modern' CSS parsing is outside of the range of this package.

**Comment by metal3d** [comment]
Yes, that's it. But, to be honest, I finally find my way by recreating pure python custom label (based on tk.Text and using marks)
This doesn't mean that I will not use your package later, I will need it for a few things.

I didn't know you are using ImageTk, there is no problems with images but maybe it is installed by dependencies and I didn't see it :)

This is what I did for my needs:
![image](https://user-images.githubusercontent.com/100080/113389230-f2520500-938f-11eb-9d58-011ef5b894c3.png)

It could be sufficient for my application (excepting that I cannot insert images) - this "Label" is named "MarkupLabel", because (like in GTK) I don't want to make a complete HTML rendering, but only use markup to process label formating. The need is to get an RSS item and format string + links. Or later, to be able to display some help text with a bit of formating.

Your package will help me with futur works. So I will keep trying et testing it,

**Comment by metal3d** [comment]
(oh I didn't mention that my work is to provide a "modern tk" package, I propose better theming and adaptation, ways to make a sidebar with toggling, MarkupLabel, and so on... Tk is not dead at all ;) )

**Comment by Andereoo** [comment]
Don't worry about it! Do whatever works best for you.

That being said, I have updated TkinterWeb. Consider re-installing it. This should fix your issue with garbled characters.

If you do decide to use this package sometime in the future, I have added the `HtmlLabel` as you have requested.

You can use `HtmlLabel(root, text="<h3 style="color:blue">Your HTML...<h3>")`. This will make a label-like widget with your HTML content inside it. Like you have asked, it does not scroll on it's own and will shrink to fit your HTML. You can check the API [here](https://github.com/Andereoo/TkinterWeb/blob/main/tkinterweb/docs/HTMLLABEL.md).

On another note, I have also made CSS cursor and hover changes much smoother and added the ability to dynamically change the zoom on the HtmlLabel and HtmlFrame, which could be useful in some future project of yours (accessibility has become a very big deal).

I really appreciate the time you have spent explaining your questions and issues in detail. Thank you!

Let me know if this helps or if you encounter any other issues!

**Comment by metal3d** [comment]
I'll take a look on Saturday, thanks a lot for this discussion and your very cool package 😄
