### ISSUE TITLE
corner radius on HtmlFrame

### ISSUE THREAD

**Issue by Guendo345** [Andereoo/TkinterWeb#51]
can you add a corner radius option for Htmlframe pls ?

**Comment by Andereoo** [comment]
Hi! 

Thanks for the suggestion. Unfortunately, that is well beyond the scope of this project, as it is an issue with the underlying HTML/CSS engine, and not with this code.

I will still look into this, however, and will let you know if I manage to introduce support for this.

**Comment by Guendo345** [comment]
all right
