### ISSUE TITLE
Select All

### ISSUE THREAD

**Issue by rodneyboyd** [Andereoo/TkinterWeb#53]
Hi, is there a way to programmatically do a "select all"? Ctrl+A doesn't work for me--is it supposed to? I simulated it by doing a find of ".*" but this highlights everything in a funky fuschia color. Also clicking on that selection with the mouse button doesn't deselect it, and the "find" selection doesn't remove an existing selection--it lurks there in the background. (I simulated "deselect" using a find of the empty string.)

Thanks!

**Comment by Andereoo** [comment]
Hi!

Thanks for the suggestion. I just added a `select_all()` command that will highlight all text in the document.

Also, if you would like, I made it possible to change the color of highlighted text. Use `yourframe.html.find_match_highlight_color = "yourcolor"` to change the green highlight colour of selected matches. Likewise, `yourframe.htmlfind_match_text_color` can be set to change the fuscia color for all other matches and  `yourframe.htmlfind_current_text_color` for the blue color used for selected text. `htmlfind_match_text_color`, `find_current_text_color`, and `selected_text_color` can also be used to set the corresponding foreground colors.

Update TkinterWeb and let me know if it works!

**Comment by rodneyboyd** [comment]
Hi, thanks for the update. It works very well. I would love to use it but the issue I reported in the issue #54 thread (menus disappearing) prevents me from incorporating this version into my app. The sample code I posted should demo the problem. Best regards, Rodney.
