### ISSUE TITLE
'HtmlFrame' object has no attribute 'get_current_link' ?

### ISSUE THREAD

**Issue by rodneyboyd** [Andereoo/TkinterWeb#54]
My code is as follows (simplified):

```
def show_help():
    help_window = tk.Toplevel(root)
    help_frame = tkinterweb.HtmlFrame(help_window, messages_enabled = False,  height=560)
    url = " etc etc ... " 
    help_frame.load_file(url, force=True)
    print('current link', help_frame.get_current_link(resolve=True))
```

This produces the error:

`AttributeError: 'HtmlFrame' object has no attribute 'get_current_link'`

(The URL does load)

`get_current_link `is directly from the documentation so I'm not sure why it seems to be unknown.

Thanks.

**Comment by Andereoo** [comment]
Hi!

I can't seem to reproduce this error.

Perhaps you have an outdated TkinterWeb installation? `get_current_link` is new in version 3.17.4. It won't work if your installation is from before February 9. Try upgrading TkinterWeb (eg. via `pip install --upgrade tkinterweb`) and let me know if the issue persists.

**Comment by rodneyboyd** [comment]
Oops! I didn't realize it was new. Works now. Thanks for your attention.

**Comment by rodneyboyd** [comment]
Um, this is weird. When I installed version 3.17.7, the menus on my app disappeared. I rolled back to 3.13.2 and the menus reappeared. Is tkinterweb doing something with the menu bar?

**Comment by Andereoo** [comment]
I'm not too sure what the problem is. Could you please upload a simplified code sample? Thanks!

**Comment by rodneyboyd** [comment]
```
import tkinter as tk
from tkinter import *
from tkinter import ttk
import sys
import tkinterweb

def hello(e=None):
    print ('hello world')
    
def create_menus():
    menu_bar = tk.Menu(window)
    window.config(menu=menu_bar)
    global file_menu
    
    file_menu = tk.Menu(menu_bar, tearoff=0)
    
    file_menu.add_command(
        label='Print',
        command=hello,
    )
    
    file_menu.add_command(
        label='Exit',
        command=sys.exit,
    )
    
    menu_bar.add_cascade(
        label="File",
        menu=file_menu,
        underline=0
    )
    
def main():
    global window
    window = tk.Tk()
    window.title("Simple Browser")

    # input_text = tk.Text(window)
    # input_text.pack()
    
    html_frame = tkinterweb.HtmlFrame(window, messages_enabled = False, width=600, height=650)

    
    html_frame.grid_propagate(0)
    html_frame.grid(row=0, column=0, sticky=N+S+E+W)
    create_menus()
    window.mainloop()
    
if __name__ == "__main__":
    main()
```

**Comment by Andereoo** [comment]
If you move `create_menus()` to above the `html_frame = tkinterweb.HtmlFrame(window, messages_enabled = False, width=600, height=650)` line, the menus should work. I'm not too sure why you notice a change in behaviour when upgrading TkinterWeb; do you happen to know what version you previously had?

**Comment by rodneyboyd** [comment]
That does work, thanks. I was using TkinterWeb 3.13.2 previously. Thanks for the speedy response and for keeping TkinterWeb "fresh". Best regards, Rodney

**Comment by Andereoo** [comment]
No worries! I looked into your issue with the menus and fixed it. It looks like a previous bug fix altered the way Tkinter loads various widgets in a way that prevents menus from loading. Feel free to upgrade TkinterWeb again and let me know if it works now!
