### ISSUE TITLE
get_current_link() not always returning link in Linux

### ISSUE THREAD

**Issue by rodneyboyd** [Andereoo/TkinterWeb#56]
My code is as follows:

```
import tkinter as tk
from tkinter import *
from tkinter import ttk

import tkinterweb
import os.path
import sys
from sys import platform

def show_me(e=None):
    print('link was: ', '[', html_frame.get_current_link(resolve=True), ']')
    
def main():
    global window
    window = tk.Tk()
    window.title("Simple Browser")
    if platform == 'win32':
        my_path = os.path.dirname(os.path.abspath(__file__)).replace('\\','/')
    elif platform == 'linux':
        my_path = os.path.dirname(os.path.abspath(__file__))
    
    global html_frame
    html_frame = tkinterweb.HtmlFrame(window, messages_enabled = False, width=300, height=350)
    url = 'file:///' + my_path + '/helptest.html'
    html_frame.grid_propagate(0)
    html_frame.grid(row=0, column=0, sticky=N+S+E+W)
    html_frame.load_file(url, force=False)
    html_frame.on_done_loading(show_me)
    
    window.mainloop()
    
if __name__ == "__main__":
    main()
```

My sample document (_helptest.html_)  is:

```
<html>
<head>
<title>Just a test</title>
</head>
<body>
<p>Click me, I'm a <a href="#target">link</a>.</p>

<h2 id="target">I'm a target!</h2>
</body>
</html>
```

On Windows, when the document is initially loaded, the url printed is blank. I don't know whether this is a bug, but it doesn't affect my code. If I click the link, the url is printed correctly. So far so good.

On Linux, again when the document initially loads the url is blank. If I click the link, the url is still printed blank. If I keep on clicking it, it continues to be blank. However, if at any point I move the mouse and then resume clicking, the url starts being printed. (This does not affect the first click. It is always blank.)

I'm using version 3.18.6 on both platforms. I'm running Ubuntu Linux via WSL.

Thanks.

**Comment by Andereoo** [comment]
Hi! Thanks for letting me know about this. This seems to be related to Bug #40, where inconsistencies with `urllib` between platforms caused issues loading websites. A similar issue was causing some URLs on Linux to not be recognized as being the same, causing the page to refresh when clicking on your link, which was causing problems. I have made a workaround for this, so you should see the same behaviour between platforms. Try upgrading TkinterWeb and let me know if it works!

Also, `get_current_link` returns the URL of a hyperlink if one is below the mouse, so it makes sense that nothing is returned after the site initially loads.

I would recommend instead using one of the methods below to handle link clicks:

```
def url_changed(url):
    # do something    
html_frame.on_url_change(url_changed)
```
or 
```
def load_new_page(url):
    ## Do stuff - insert code here
    html_frame.load_url(url) #load the new website
    
html_frame.on_link_click(load_new_page)
```

**Comment by rodneyboyd** [comment]
Hi, it's looking good now. Thanks for the update!
