### ISSUE TITLE
Feature request: select/highlight line

### ISSUE THREAD

**Issue by rodneyboyd** [Andereoo/TkinterWeb#57]
When a user clicks in the HTML frame, I'd like to programmatically select or highlight the current line. By highlight I mean something like tags in tk.Text objects.

```
def handle_click(e=None):
    html_frame.select_line()
    # or
    html_frame.select_line(e.x, e.y)
```
It would be nice to be able to choose the select or highlight color. Presumably a subsequent select would erase the current selection, but for highlights maybe there would be the option to have them persist.

Thanks.

**Comment by Andereoo** [comment]
Hi! Thanks for the request.

Would using CSS tags (either through `add_css()` in Python or `:active` in CSS, for instance) not be best for this situation?

**Comment by rodneyboyd** [comment]
Thanks for the suggestions. I'll try it and let you know how it works out.

**Comment by rodneyboyd** [comment]
I used ` :hover` and it did what I wanted, thanks. However in the process I discovered a bug--will add an issue.
