### ISSUE TITLE
Feature request: Navigation keys

### ISSUE THREAD

**Issue by rodneyboyd** [Andereoo/TkinterWeb#58]
It's nice that HTMLFrame adds its own vertical scrollbar, but the navigation keys PageUp, PageDown, Home, and End don't seem to have any effect. 

Thanks.

**Comment by Andereoo** [comment]
Hi!

Right now these keys are not bound by default. I try to keep bindings to a minimum because they might conflict with the code running TkinterWeb. To bind PageUp and PageDown, you could use:

```
frame.bind_all("<Prior>", lambda e: frame.html.yview_scroll(-5, "units"))
frame.bind_all("<Next>", lambda e: frame.html.yview_scroll(5, "units"))
```

Do you think it would be better to provide these bindings by default?

**Comment by rodneyboyd** [comment]
I see your point about the bindings. Maybe if you included them as a useful tip in the documentation that would be enough.

What you suggested worked (I used 25, not 5). Thanks.
