### ISSUE TITLE
Can't submit some forms

### ISSUE THREAD

**Issue by maxim3007** [Andereoo/TkinterWeb#6]
I have checked google and badssl forms.

`import tkinter as tk`
`import tkinterweb as tw`
`import tkinter.messagebox as msb`
`root = tk.Tk()`
`frame = tw.HtmlFrame(root)`
`frame.on_form_submit(lambda *_: msb.showinfo("Form", "Form"))`
`frame.pack()`
`frame.load_website('http://very.badssl.com')`
`root.mainloop()`

If form works the app will show a message box

google (message)
badssl (no message)

OS:
    macOS Catalina 64-bit (python 3.9)
    Windows 7 32-bit (python 3.7)

PS: sorry for my english

**Comment by Andereoo** [comment]
Thank you very much for letting me know about this issue. 
I have added a fix into today's release. Consider upgrading TkinterWeb. That should fix this issue. 

Please do let me know if this issue still persists and/or if you encounter any other issues!
