### ISSUE TITLE
Enhancement request: Support for HTML4/HTML5 id values

### ISSUE THREAD

**Issue by rodneyboyd** [Andereoo/TkinterWeb#62]
HTML4 allows periods and colons in ID attribute values: https://www.w3.org/TR/html4/types.html#type-id
HTML5 allows almost anything: https://html.spec.whatwg.org/multipage/dom.html#the-id-attribute

However if a URL ending with '#' plus a string containing period or colon is loaded, the widget crashes.

At least it shouldn't crash. Ideally HTML5 ids would be supported.

Thanks!

**Comment by Andereoo** [comment]
Thanks for letting me know about this. I agree that it would be nice to see support for HTML5 ids, but that is a question for the underlying HTML engine and is beyond the scope of this project.

That being said, I introduced some logic that strips problematic characters from URL fragments (the part after the '#'). Upgrading TkinterWeb should fix the crashes. It's not ideal, but it's the best I can do.

Hopefully this helps.

**Comment by rodneyboyd** [comment]
> that is a question for the underlying HTML engine and is beyond the scope
of this project

I was afraid you'd say that 😉

Thanks for the fix.
