### ISSUE TITLE
css not working

### ISSUE THREAD

**Issue by oberluz** [Andereoo/TkinterWeb#71]
Hi,

I loaded the styles.css generated by pygmentize using the html_frame.add_css method and then called  html_frame.load_html with some html code that uses the styles but they are not rendered in colour.

The only way I can get it to render them is to call   html_frame.load_html(<style>'+self.css+'</style>' + html) and this works also without calling  html_frame.add_css.

am I using html_frame.add_css incorrectly?

**Comment by oberluz** [comment]
i just tried reversing the calls and it works fine in this order:

```
html_frame.load_html(html)
html_frame.add_css(css)
```

Maybe this should be stated in the docs...

**Comment by Andereoo** [comment]
Hi! `load_html` clears the current page, including CSS. If you want to set the CSS before adding the HTML, use `add_html` instead. Good idea - I'll tweak the docs to make that more clear.

**Comment by oberluz** [comment]
makes sense now. thanks!

**Comment by oberluz** [comment]
makes sense now. Great project BTW, thanks!

**Comment by Andereoo** [comment]
No worries! Let me know if you have any other questions!

**Comment by oberluz** [comment]
Not sure if I've found a bug but if I do:
`                self.description_text.html.reset()
                self.description_text.add_css(self.css)
                self.description_text.add_html(html)
`
instead of
`
                self.description_text.add_html(html)
                self.description_text.add_css(self.css)
` 
the images in the html are not displayed

**Comment by Andereoo** [comment]
No worries! Let me know if you have any other questions!

**Comment by Andereoo** [comment]
Could you give me some sample code?

**Comment by oberluz** [comment]
Run the following with a image.png in the same directory

```
from tkinterweb import HtmlFrame
from tkinter import Tk


class Window(Tk):
    def __init__(self):
        super().__init__()
        self.frame = HtmlFrame(self, height='5', messages_enabled=False)
        html = """
<h1>html with image</h1>
<p><img alt="" src="image.png" /></p>
<p>some text</p>
        """
        # works
        self.frame.load_html(html)
        self.frame.pack()

        # does not work
        # self.frame.html.reset()  # I need a reset so that the new content is not appended to the previous content
        # self.frame.add_html(html)
        # self.frame.pack()


def main():
    window = Window()
    window.mainloop()


if __name__ == '__main__':
    main()  # pragma: no cover
```

**Comment by oberluz** [comment]
I raised https://github.com/Andereoo/TkinterWeb/issues/72 to deal with this as a separate issue as this issue is closed anyway.
