### ISSUE TITLE
add_html fails to render images

### ISSUE THREAD

**Issue by oberluz** [Andereoo/TkinterWeb#72]
add_html fails to render an img tag.

To reproduce run the following with an image.png in the same directory

```python
from tkinterweb import HtmlFrame
from tkinter import Tk


class Window(Tk):
    def __init__(self):
        super().__init__()
        self.frame = HtmlFrame(self, height='5', messages_enabled=False)
        html = """
<h1>html with image</h1>
<p><img alt="" src="image.png" /></p>
<p>some text</p>
        """
        # works
        # self.frame.load_html(html)
        # self.frame.pack()

        # does not work
        self.frame.html.reset() 
        self.frame.add_html(html)
        self.frame.pack()


def main():
    window = Window()
    window.mainloop()


if __name__ == '__main__':
    main()  # pragma: no cover
```

still breaks even without the call to reset

**Comment by Andereoo** [comment]
Hi!

Apologies for the delay. `add_html` is intended to be used after the document loads. It was missing the logic that sets the base url of the document, which is used when loading images and stylesheets. I fixed this issue. Try upgrading TkinterWeb, and let me know if it works!

**Comment by oberluz** [comment]
Hi,

I will, many thanks

Cheers
