### ISSUE TITLE
Check if image has loaded?

### ISSUE THREAD

**Issue by Zamy846692** [Andereoo/TkinterWeb#73]
Is there any function / method that will return the result of whether an image has loaded or not? thanks.

**Comment by Andereoo** [comment]
Hi! Could you please elaborate on exactly what you are trying to do? If you could provide an example that would be great. There is no direct way at the moment, but there are still plenty of workarounds that might work for your case.

**Comment by Zamy846692** [comment]
The idea is that if the image source (which is a URL) doesn't exist, a back up source can be used to replace it. In the same vain as this: https://stackoverflow.com/questions/9022427/see-if-src-of-img-exists.

The source attributes are created dynamically using a python script.

**Comment by Andereoo** [comment]
There are a few things we could do here, let me know what works best for you:

1. Check that the files or urls exist before sending them to TkinterWeb. I wouldn't recommend this if you are dealing with online images.
2. Set `yourframe.ignore_invalid_images(False)` and set `yourframe.html.broken_image = some_raw_image_data`. If all of your images that fail to load are going to be changed to the same picture, this is a fantastic solution.
3. If the above options don't suit your needs, I could add an option that lets you add Python function that will be called every time an image fails to load, similar to the `onerror` property used in the link you provided. We could always have it send the url of the image in question too, if you need to be able to tell which url was problematic.

Let me know what is best!

**Comment by Zamy846692** [comment]
3.

I have previously tried option 1 but it was painfully inefficient and slow

**Comment by Andereoo** [comment]
Hi! Thanks for looking into this. I'm away for the summer and don't have access to a computer. I'll implement option 3 in September when I return. I hope this isn't too much of a nuisance.

**Comment by Zamy846692** [comment]
Some time ago I was able to add a modification to the `fetch_images` function, which triggers a tkinter binding event an image error occurs

`def fetch_images(self, url, name, urltype):
        """Fetch images and display them in the document"""
        thread = self.begin_download()

        path = urlparse(url).path
        self.message_func("Fetching image: {0}.".format(shorten(url)))

        def fetch_images_url_error():
            for node in self.search("img"):
                try:
                    if self.get_node_attribute(node, "src") == url: self.on_error_func( node )
                except Exception: continue

        try:
            if url.startswith("file://") or (not self.caches_enabled):
                data, newurl, filetype = download(url)
            else:
                data, newurl, filetype = cachedownload(url)

            if self.unstoppable and data:
                image, error = newimage(data, name, filetype, self.image_inversion_enabled)

                if image:
                    self.loaded_images.add(image)
                elif error == "no_pycairo":
                    self.message_func(
                        "Scalable Vector Graphics could not be shown because Pycairo is not installed but is required to parse .svg files.")
                    fetch_images_url_error()
                elif error == "no_rsvg":
                    self.message_func(
                        "Scalable Vector Graphics could not be shown because Rsvg is not installed but is required to parse .svg files.")
                    fetch_images_url_error()
                elif error == "corrupt":
                    self.message_func(
                        "The image {} could not be shown.".format(url))
                    fetch_images_url_error()

        except Exception:
            self.message_func(
                "The image {} could not be shown because it is corrupt or is not supported yet.".format(url))

            fetch_images_url_error()

        self.finish_download(thread)`

HtmlFrame Class

`   def add_css(self, css_source):
        "Parse CSS code"
        self.html.parse_css(data=css_source)
        
    def on_error(self, function):
    
        self.html.on_error_func = function`

**Comment by Andereoo** [comment]
Glad you figured this out! Sorry for the delay. I just implemented something similar. If you want, you can now use `frame.on_image_setup(function)`. Whenever an image is parsed, its url will be passed to your function as well as a boolean variable that is set to True if it was successfully loaded and False if it could not be displayed.
