### ISSUE TITLE
It appears that `HtmlFrame.add_css` is broken.

### ISSUE THREAD

**Issue by aponigricon** [Andereoo/TkinterWeb#77]
First of all thank you to @Andereoo for this wonderful library. I am aware that you are away from the summer, I'm just bringing attention to an issue for whenever.

Anyways, I just wanted to report that it appears that `HtmlFrame.add_css` is broken. Even injecting something as simple as `*{color: blue;}` doesn't do anything. Also doesn't work if I don't use a selector at all, though that's expected.

I should note that inserting a `<link>` tag to a stylesheet in the header before passing the html file into the HtmlFrame instance works perfectly fine. The HtmlFrame renders almost anything I throw at it in this manner, it's just that the `add_css` method doesn't do anything.

Best regards.

### **EDIT:**

After testing more cases, it does actually seem to work, but the `!important` tag does not, and the rendering engine is thus unable to override styles applied with the `style` attribute directly in the DOM. This is very odd, seeing as the `!important` tag works fine in stylesheets loaded via link.

I guess I'll leave the issue open for now in case you want to take a look at this special case, but just know that to reproduce it you need an html file with a style applied via the `style` attribute of an element. `HtmlFrame.add_css` is unable to override any styles applied in this manner, even with the `!importan` tag.

**Comment by Andereoo** [comment]
Thanks for bringing this to my attention! I've fixed this issue; stylesheets loaded via `add_css` should now take precedence over all others and any CSS added while the page is still loading will no longer be ignored. Try upgrading TkinterWeb, and let me know how it works!
