### ISSUE TITLE
Feature request: support for small-caps

### ISSUE THREAD

**Issue by rodneyboyd** [Andereoo/TkinterWeb#79]
The CSS style `font-variant: small-caps` currently has no effect. It would be nice to have :) Thanks!

**Comment by Andereoo** [comment]
Hi! Unfortunately `font-variant: small-caps` is not supported by the underlying Tkhtml3 HTML engine. Adding support is well beyond the scope of this project. Feel free to take a look at http://tkhtml.tcl.tk/support.html. Sorry I couldn't be more helpful here.
