### ISSUE TITLE
[Suggestion] split get_node_attribute into 2 methods

### ISSUE THREAD

**Issue by Zamy846692** [Andereoo/TkinterWeb#81]
`get_node_attribute ` is essentially 2 methods in 1, the first to set an attribute  if `value` exists, and the second to get the attribute else it dose not.
I find it quite misleading and think it would be greatly simplified if it was split into:

    def get_node_attribute(self, node_handle, attribute, default=""):
        """Get the specified attribute of the given node"""
        return self.tk.call(node_handle, "attribute", "-default", default, attribute)
and

    def set_node_attribute(self, node_handle, attribute, value):
        """Set the specified attribute of the given node"""
        return self.tk.call(node_handle, "attribute", attribute, value)`

Or at least be renamed to `node_attribute`, since the 'get' implies it can only return a variable.

**Comment by Andereoo** [comment]
Hi! Thanks for the suggestion. I've implemented your suggestion. For backwards compatibility, `get_node_attribute` can still be used to set the value of the node's attribute, but there is now a `set_node_attribute` function as well.
