### ISSUE TITLE
PIL not working. 

### ISSUE THREAD

**Issue by HelikopterX** [Andereoo/TkinterWeb#82]
TkinterWeb is clearly bugging right now :skull:.

The error report is here:
ModuleNotFoundError: The files required to run TkinterWeb could not be found. This usually occurs when bundling TkinterWeb into an app without forcing the application maker to include all nessessary files or when some of TkinterWeb's dependencies are not installed. See https://github.com/Andereoo/TkinterWeb/blob/main/tkinterweb/docs/FAQ.md for more information. 

Error code: Traceback (most recent call last):
  File "/home/dogcmamere/.local/lib/python3.9/site-packages/tkinterweb/__init__.py", line 31, in <module>
    from bindings import TkinterWeb
  File "/home/dogcmamere/.local/lib/python3.9/site-packages/tkinterweb/bindings.py", line 39, in <module>
    from imageutils import *
  File "/home/dogcmamere/.local/lib/python3.9/site-packages/tkinterweb/imageutils.py", line 28, in <module>
    from PIL.ImageTk import PhotoImage
ModuleNotFoundError: No module named 'PIL.ImageTk'
 
If you think this is a bug, please file a bug report at https://github.com/Andereoo/TkinterWeb.

**Comment by HelikopterX** [comment]
The error is

**Comment by HelikopterX** [comment]
The error is easy to remove. Pillow must be installed with version **10.0.0** specifically

**Comment by HelikopterX** [comment]
Or it will crash

**Comment by Andereoo** [comment]
Thanks for letting me know about this! From the error it looks like you were missing ImageTk. I can't reproduce this issue but I'm glad you figured it out.
