### ISSUE TITLE
Почему не поддерживает файл png?

### ISSUE THREAD

**Issue by LeonardNekit** [Andereoo/TkinterWeb#84]
В гугле работает а так нет,почему?

**Comment by LeonardNekit** [comment]
Я пробовал через load_html() и выяснилось что формат png явно не принимает, только формат jpeg

**Comment by Andereoo** [comment]
Можете ли вы предоставить код, который не работает? Спасибо!

**Comment by LeonardNekit** [comment]
Сейчас только что проверил, заработало. Из-за последнего обновление, почаще бы таких исправлений

**Comment by Andereoo** [comment]
Звучит отлично! Дайте мне знать, если у вас возникнут другие вопросы или вы
обнаружите ошибку.
